name: Sync Multiple Images to Docker Hub

on:
  workflow_dispatch:
    inputs:
      image_names_tags:
        description: 'List of full image names and tags separated by commas (e.g., myimage1:v1,myimage2:v2)'
        required: true

jobs:
  sync-to-docker-hub:
    runs-on: ubuntu-latest
    steps:
    - name: Install Skopeo
      run: |
        echo 'deb http://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_20.04/ /' | sudo tee /etc/apt/sources.list.d/devel:kubic:libcontainers:stable.list
        curl -L "https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_20.04/Release.key" | sudo apt-key add -
        sudo apt-get update
        sudo apt-get install -y skopeo

    - name: Login to GitHub Container Registry
      run: echo ${{ secrets.GHCR_TOKEN }} | skopeo login ghcr.io --username ${{ github.repository_owner }} --password-stdin

    - name: Login to Docker Hub
      run: echo ${{ secrets.DOCKER_HUB_TOKEN }} | skopeo login docker.io --username ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin

    - name: Sync Image
      run: |
        IFS=',' read -ra IMAGES <<< "${{ github.event.inputs.image_names_tags }}"
        for image in "${IMAGES[@]}"; do
          skopeo copy \
            docker://ghcr.io/${{ github.repository_owner }}/$image \
            docker://docker.io/${{ secrets.DOCKER_HUB_USERNAME }}/$image
        done
